# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('sum_formula', models.TextField(null=True)),
                ('MCFID', models.TextField(default='')),
            ],
        ),
    ]
