# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nM', models.IntegerField(default=1)),
                ('delta_formula', models.TextField(default='')),
                ('delta_atoms', models.TextField(default='')),
                ('charge', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_finished', models.BooleanField(default=False)),
                ('name', models.TextField(default='')),
                ('mass_accuracy_ppm', models.FloatField(default=10.0)),
                ('quad_window_mz', models.FloatField(default=1.0)),
                ('intrument', models.TextField(default='')),
                ('adducts_present', models.ManyToManyField(blank=True, to='standards_review.Adduct')),
            ],
        ),
        migrations.CreateModel(
            name='FragmentationSpectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precursor_mz', models.FloatField(null=True)),
                ('ms1_intensity', models.FloatField(default=0.0)),
                ('_centroid_mzs', models.TextField()),
                ('_centroid_ints', models.TextField()),
                ('collision_energy', models.TextField(default='')),
                ('spec_num', models.IntegerField(blank=True, null=True)),
                ('rt', models.FloatField(blank=True, null=True)),
                ('precursor_quad_fraction', models.FloatField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=0)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_edited', models.DateField(default=django.utils.timezone.now)),
                ('adduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Adduct')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards_review.Dataset')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_adduct_mzs', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('sum_formula', models.TextField(null=True)),
                ('inchi_code', models.TextField(default='')),
                ('exact_mass', models.FloatField(default=0.0)),
                ('solubility', models.TextField(blank=True, null=True)),
                ('hmdb_id', models.TextField(blank=True, null=True)),
                ('chebi_id', models.TextField(blank=True, null=True)),
                ('lipidmaps_id', models.TextField(blank=True, null=True)),
                ('cas_id', models.TextField(blank=True, null=True)),
                ('pubchem_id', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCFID', models.IntegerField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('vendor_cat', models.TextField(blank=True, null=True)),
                ('lot_num', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('molecule', models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='standards_review.Molecule')),
            ],
        ),
        migrations.CreateModel(
            name='Xic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz', models.FloatField(default=0.0)),
                ('_xic', models.TextField(blank=True, db_column='data')),
                ('_rt', models.TextField(blank=True, db_column='rt_data')),
                ('collision', models.TextField(default='')),
                ('adduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Adduct')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards_review.Dataset')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Standard')),
            ],
        ),
        migrations.AddField(
            model_name='fragmentationspectrum',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Standard'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='standards_present',
            field=models.ManyToManyField(blank=True, to='standards_review.Standard'),
        ),
    ]
