# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 13:23
from __future__ import unicode_literals

from django.db import migrations

view_name = "standards_review_moleculespectracount"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('standards_review', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            DROP VIEW IF EXISTS {};
            CREATE VIEW {} AS
                SELECT std.molecule_id, COUNT(DISTINCT spec.id) spectra_count
                FROM standards_review_standard std
                  LEFT OUTER JOIN standards_review_fragmentationspectrum spec
                    ON std.id = spec.standard_id
                GROUP BY std.molecule_id;""".format(view_name, view_name))
    ]
