# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0002_moleculespectracount_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeSpectraCount',
            fields=[
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='standards_review.Molecule')),
                ('spectra_count', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='standard',
            name='molecule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards_review.Molecule'),
        ),
        migrations.AddField(
            model_name='processingerror',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards_review.Dataset'),
        ),
    ]
