# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0002_auto_20160112_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField(default='')),
                ('offset', models.FloatField(default=0.0)),
                ('charge', models.IntegerField(default=1)),
                ('datasets_present_in', models.ManyToManyField(to='standards_review.Dataset')),
            ],
        ),
    ]
