# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0003_adduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz', models.FloatField(default=0.0)),
                ('_xic', models.TextField(blank=True, db_column='data')),
                ('adduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Adduct')),
                ('datasets_present_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards_review.Dataset')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Standard')),
            ],
        ),
    ]
