# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0003_auto_20160616_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='molecule',
            name='tags',
            field=models.ManyToManyField(to='standards_review.MoleculeTag'),
        ),
    ]
