# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0003_auto_20160616_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeTag',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='molecule',
            name='tags',
            field=models.ManyToManyField(to='standards_review.MoleculeTag'),
        ),
    ]
