# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0004_auto_20160816_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='tags',
            field=models.ManyToManyField(blank=True, to='standards_review.MoleculeTag'),
        ),
    ]
