# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0004_xic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xic',
            old_name='datasets_present_in',
            new_name='dataset',
        ),
    ]
