# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0005_auto_20160825_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='intrument',
        ),
        migrations.AddField(
            model_name='dataset',
            name='lc_info',
            field=models.ManyToManyField(to='standards_review.LcInfo'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='ms_info',
            field=models.ManyToManyField(to='standards_review.MsInfo'),
        ),
    ]
