# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0007_auto_20160424_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='molecule',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='standards_review.Molecule'),
        ),
    ]
