# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0007_instrumentinfo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='natural_product',
            field=models.BooleanField(default=True),
        ),
    ]
