# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0008_natural_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='ion_analyzer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='ionization_method',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
