# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0009_massbank_instrumentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
