# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0009_standard_exact_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='exact_mass',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
