# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0011_auto_20160116_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduct',
            old_name='formula',
            new_name='delta_atoms',
        ),
        migrations.RemoveField(
            model_name='adduct',
            name='offset',
        ),
        migrations.AddField(
            model_name='adduct',
            name='delta_formula',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='adduct',
            name='nM',
            field=models.IntegerField(default=1),
        ),
    ]
