# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0011_auto_20170311_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragmentationspectrum',
            name='_splash',
            field=models.TextField(default='', null=True),
        ),
    ]
