# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0013_auto_20160116_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='adducts_present',
            field=models.ManyToManyField(blank=True, null=True, to='standards_review.Adduct'),
        ),
    ]
