# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0014_auto_20160116_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='mass_accuracy_ppm',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='adducts_present',
            field=models.ManyToManyField(blank=True, to='standards_review.Adduct'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='standards_present',
            field=models.ManyToManyField(blank=True, to='standards_review.Standard'),
        ),
    ]
