# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0015_auto_20160116_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='xic',
            name='_rt',
            field=models.TextField(blank=True, db_column='rt_data'),
        ),
    ]
