# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0017_auto_20160117_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentationspectrum',
            name='adduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Adduct'),
        ),
    ]
