# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0019_dataset_quad_window_mz'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentationspectrum',
            name='precursor_quad_fraction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
