# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0020_fragmentationspectrum_precursor_quad_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragmentationspectrum',
            name='reviewed',
            field=models.BooleanField(default=0),
        ),
    ]
