# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0021_fragmentationspectrum_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='inchi_code',
            field=models.TextField(default=''),
        ),
    ]
