# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0022_standard_inchi_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='avanti_cat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='cas_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='chebi_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='hmdb_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='lipidmaps_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='sigma_cat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard',
            name='solubility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
