# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0023_auto_20160128_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='avanti_cat',
            new_name='pubchem_id',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='sigma_cat',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='standard',
            name='vendor_cat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
