# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0024_auto_20160202_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='_adduct_mzs',
            field=models.TextField(default=''),
        ),
    ]
