# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0025_standard__adduct_mzs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField(blank=True, null=True)),
                ('vendor_cat', models.TextField(blank=True, null=True)),
                ('lot_num', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='standard',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='vendor_cat',
        ),
    ]
