# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0027_auto_20160208_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_adduct_mzs', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('sum_formula', models.TextField(null=True)),
                ('MCFID', models.TextField(default='')),
                ('inchi_code', models.TextField(default='')),
                ('exact_mass', models.FloatField(default=0.0)),
                ('solubility', models.TextField(blank=True, null=True)),
                ('hmdb_id', models.TextField(blank=True, null=True)),
                ('chebi_id', models.TextField(blank=True, null=True)),
                ('lipidmaps_id', models.TextField(blank=True, null=True)),
                ('cas_id', models.TextField(blank=True, null=True)),
                ('pubchem_id', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='standard',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='cas_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='chebi_id',
            new_name='lot_num',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='hmdb_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='lipidmaps_id',
            new_name='vendor_cat',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='MCFID',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='_adduct_mzs',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='exact_mass',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='inchi_code',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='pubchem_id',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='solubility',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='sum_formula',
        ),
        migrations.AddField(
            model_name='standard',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AddField(
            model_name='standard',
            name='standard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='standards_review.Molecule'),
        ),
    ]
