# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0029_auto_20160208_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecule',
            name='MCFID',
        ),
        migrations.AddField(
            model_name='standard',
            name='MCFID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
