# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0031_auto_20160209_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='intrument',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fragmentationspectrum',
            name='collision_energy',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fragmentationspectrum',
            name='ms1_intensity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='xic',
            name='collision',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='standard',
            name='molecule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='standards_review.Molecule'),
        ),
    ]
