# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0032_auto_20160307_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='molecule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='standards_review.Molecule'),
        ),
    ]
