# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standards_review', '0033_auto_20160317_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='processing_finished',
            field=models.BooleanField(default=False),
        ),
    ]
